// Floor Plan Data — centralized model data for dynamic /floor-plans/[slug] pages

export interface FloorPlan {
  slug: string;
  name: string;
  series: string;
  type: "Single Wide" | "Double Wide" | "Modular";
  code: "HUD" | "IRC";
  sqft: number;
  beds: number;
  baths: number;
  sections: string;
  price: string;
  priceNumeric: string;
  sku: string;
  description: string;
  heroImage: string;
  heroImageAlt: string;
  features: string[];
  specs: Record<string, string>;
  faqs: Array<{ question: string; answer: string }>;
}

export const floorPlans: FloorPlan[] = [
  {
    slug: "aspire-1456",
    name: "Aspire 1456",
    series: "Aspire Series",
    type: "Single Wide",
    code: "HUD",
    sqft: 1008,
    beds: 2,
    baths: 2,
    sections: "Single Section",
    price: "$55,000",
    priceNumeric: "55000",
    sku: "ASP-1456",
    description: "The Aspire 1456 is a thoughtfully designed 2-bedroom, 2-bathroom single wide home offering 1,008 square feet of comfortable living space. Featuring an open-concept kitchen and living area, this home maximizes every inch with smart design. Perfect for first-time buyers, downsizers, or anyone seeking quality affordable homeownership.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Aspire 1456 single wide manufactured home exterior",
    features: [
      "Open-Concept Kitchen & Living",
      "2 Full Bathrooms",
      "Master Suite",
      "Energy-Efficient Windows",
      "Modern Cabinetry",
      "Utility Room",
      "Customizable Finishes",
    ],
    specs: {
      width: "14-16 ft",
      length: "63 ft",
      ceiling: "8' ceilings",
      bedrooms: "2",
      bathrooms: "2 full",
      kitchen: "Open concept with dining area",
      living: "Combined living/dining",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Aspire 1456 cost?", answer: "The Aspire 1456 starts at $55,000 for the base home. Total cost depends on delivery distance, site preparation, foundation type, and utility connections. Factory Direct Homes Center provides transparent line-item pricing so you see exactly what every component costs with no hidden markups or surprise fees." },
      { question: "What financing is available for the Aspire 1456?", answer: "The Aspire 1456 qualifies for chattel loans, FHA Title I and Title II loans, VA loans for veterans, and conventional mortgages when placed on a permanent foundation with owned land. Our lending partners include 21st Mortgage, Triad Financial, and Credit Human Federal Credit Union." },
      { question: "Can I customize the Aspire 1456?", answer: "Yes, every Champion home is customizable. You can choose flooring types, cabinetry styles, countertop materials, appliance packages, exterior colors, and interior finishes. Our team walks you through all available options during your showroom visit or consultation to create your perfect home." },
      { question: "How long does delivery take for the Aspire 1456?", answer: "From order to move-in typically takes 8 to 12 weeks. Factory build time is 4 to 6 weeks at Champion's Topeka, Indiana facility. Site preparation should happen during the build. Delivery and setup take 1 to 2 weeks. We coordinate the entire process from order through final inspection." },
      { question: "Is the Aspire 1456 a good starter home?", answer: "The Aspire 1456 is an excellent starter home. At 1,008 square feet with 2 bedrooms and 2 bathrooms, it provides comfortable living at an affordable price point. The open-concept design makes the space feel larger, and the two full bathrooms add convenience for couples or small families." },
    ],
  },
  {
    slug: "aspire-1672",
    name: "Aspire 1672",
    series: "Aspire Series",
    type: "Single Wide",
    code: "HUD",
    sqft: 1152,
    beds: 3,
    baths: 2,
    sections: "Single Section",
    price: "$62,000",
    priceNumeric: "62000",
    sku: "ASP-1672",
    description: "The Aspire 1672 delivers 3-bedroom living in an efficient single wide format. At 1,152 square feet, this home features a master suite with walk-in closet, two additional bedrooms, and two full bathrooms. An ideal choice for growing families who want quality and affordability.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Aspire 1672 single wide manufactured home with 3 bedrooms",
    features: [
      "Master Suite with Walk-in Closet",
      "3 Bedrooms",
      "2 Full Bathrooms",
      "Open Living Area",
      "Modern Kitchen",
      "Energy-Efficient Construction",
      "Customizable Options",
    ],
    specs: {
      width: "16 ft",
      length: "72 ft",
      ceiling: "8' ceilings",
      bedrooms: "3",
      bathrooms: "2 full",
      kitchen: "Galley style with dining nook",
      living: "Open living room",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Aspire 1672 cost?", answer: "The Aspire 1672 starts at $62,000 for the base home. Total cost includes delivery, setup, foundation, and utility connections which vary by location and site conditions. We provide detailed line-item pricing with no hidden fees so you can budget accurately for your total home investment." },
      { question: "Is 3 bedrooms enough for a family?", answer: "Three bedrooms works well for most families. The Aspire 1672 gives parents a private master suite with walk-in closet while children share or each get their own room. The efficient layout maximizes usable space, and at $62,000 starting price it's significantly more affordable than larger alternatives." },
      { question: "Can I customize the Aspire 1672?", answer: "Yes, the Aspire 1672 offers full customization through Champion Homes. Choose your flooring, cabinetry, countertops, appliance package, exterior colors, and interior finishes. Popular upgrades include upgraded kitchen countertops, premium flooring, and enhanced bathroom fixtures. Visit our showroom to see options in person." },
      { question: "What is the difference between the Aspire 1456 and 1672?", answer: "The main differences are size and bedrooms. The Aspire 1672 offers 1,152 square feet with 3 bedrooms compared to the 1456's 1,008 square feet with 2 bedrooms. The 1672 adds a master suite with walk-in closet. The 1672 costs about $7,000 more but provides significantly more living space for families." },
      { question: "How energy efficient is the Aspire 1672?", answer: "The Aspire 1672 meets or exceeds HUD energy efficiency standards. Factory construction ensures precise insulation installation, tight building envelope, and quality windows throughout. Owners typically see lower utility bills compared to older homes of similar size. ENERGY STAR upgrades are available for additional savings." },
    ],
  },
  {
    slug: "dutch-1460",
    name: "Dutch 1460",
    series: "Dutch Series",
    type: "Single Wide",
    code: "HUD",
    sqft: 840,
    beds: 2,
    baths: 1,
    sections: "Single Section",
    price: "$52,000",
    priceNumeric: "52000",
    sku: "DUT-1460",
    description: "The Dutch 1460 is our most affordable home, delivering smart design in a compact 840 square foot package. With 2 bedrooms and 1 bathroom, this home is perfect for first-time buyers, retirees, or anyone who values simplicity and value. Quality Champion construction at an entry-level price.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Dutch 1460 compact single wide manufactured home",
    features: [
      "Most Affordable Option",
      "Compact & Efficient Design",
      "2 Bedrooms",
      "Full Bathroom",
      "Open Kitchen/Living",
      "Low Utility Costs",
      "Customizable Finishes",
    ],
    specs: {
      width: "14 ft",
      length: "60 ft",
      ceiling: "8' ceilings",
      bedrooms: "2",
      bathrooms: "1 full",
      kitchen: "Efficient layout with counter space",
      living: "Combined living area",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Dutch 1460 cost?", answer: "The Dutch 1460 starts at $52,000, making it our most affordable new home option. Total cost with delivery, setup, and site work typically ranges from $65,000 to $85,000 depending on your location and site conditions. We provide transparent line-item pricing so you can plan your budget with confidence." },
      { question: "Who is the Dutch 1460 best for?", answer: "The Dutch 1460 is ideal for first-time homebuyers on a budget, retirees looking to downsize, singles or couples without children, or anyone who wants an affordable path to homeownership. At 840 square feet, it offers comfortable living without the burden of a large mortgage payment." },
      { question: "Can I get a loan for a $52,000 manufactured home?", answer: "Yes. Chattel loans from our partners like 21st Mortgage are available for homes at this price point with credit scores as low as 575. Monthly payments on a $52,000 home can be as low as $400-500 depending on your down payment and loan terms. FHA and VA loans are also options with qualifying foundations." },
      { question: "Is 840 square feet enough space?", answer: "For one or two people, 840 square feet provides comfortable living. The Dutch 1460's efficient layout includes a separate bedroom, full bathroom, and open kitchen and living area. Many buyers find this size ideal because it means lower utility bills, less maintenance, and more affordable monthly payments." },
      { question: "Can I customize the Dutch 1460?", answer: "Yes, even our most affordable home offers Champion's customization options. Choose your flooring, cabinetry, countertops, exterior finishes, and more. While the layout is fixed, the finishes can be tailored to your taste. Visit our Auburn showroom to see material samples and discuss your options." },
    ],
  },
  {
    slug: "brighton-2856",
    name: "Brighton 2856",
    series: "Brighton Series",
    type: "Double Wide",
    code: "HUD",
    sqft: 1493,
    beds: 3,
    baths: 2,
    sections: "Multi-Section",
    price: "$89,900",
    priceNumeric: "89900",
    sku: "BRI-2856",
    description: "The Brighton 2856 is our most popular double wide, offering 1,493 square feet of open-concept living. The split bedroom design gives the master suite privacy while the island kitchen serves as the heart of the home. Three bedrooms and two bathrooms provide room for the whole family.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Brighton 2856 double wide manufactured home with split bedroom design",
    features: [
      "Split Bedroom Design",
      "Island Kitchen",
      "Open-Concept Living",
      "3 Bedrooms",
      "2 Full Bathrooms",
      "Master Suite with En-Suite",
      "Spacious Living Room",
      "Customizable Finishes",
    ],
    specs: {
      width: "28 ft",
      length: "56 ft",
      ceiling: "8-9' ceilings",
      bedrooms: "3 (split design)",
      bathrooms: "2 full",
      kitchen: "Island kitchen with pantry",
      living: "Open concept living/dining",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Brighton 2856 cost?", answer: "The Brighton 2856 starts at $89,900 for the base home. This is our most popular double wide because it offers excellent value with 1,493 square feet, split bedrooms, and an island kitchen. Total installed cost varies by location and site preparation needs. We provide complete line-item pricing with no hidden fees." },
      { question: "What does split bedroom design mean?", answer: "A split bedroom design places the master suite on one side of the home and the secondary bedrooms on the opposite side, with the living areas in between. This gives the master bedroom more privacy and separates adults from children's rooms. It's the most requested layout feature in our double wide homes." },
      { question: "Can the Brighton 2856 fit on my lot?", answer: "The Brighton 2856 requires a minimum lot width of about 35 feet and length of 60 feet, plus setback requirements from property lines. Most standard lots in Indiana, Ohio, and Michigan accommodate this size. Check your local zoning regulations or contact us and we can help verify your lot dimensions." },
      { question: "What financing options work for the Brighton 2856?", answer: "At $89,900, the Brighton 2856 qualifies for chattel loans, FHA loans, VA loans for veterans, and conventional mortgages when on a permanent foundation with owned land. Monthly payments typically range from $650 to $900 depending on your loan type, down payment, and credit score." },
      { question: "How does the Brighton 2856 compare to site-built homes?", answer: "The Brighton 2856 delivers comparable quality to site-built homes at roughly 40-50% less cost per square foot. Factory construction means precision building, quality materials, and no weather delays. The main difference is construction method, not quality. Many visitors to our showroom are surprised by the build quality." },
    ],
  },
  {
    slug: "brighton-2852",
    name: "Brighton 2852",
    series: "Brighton Series",
    type: "Double Wide",
    code: "HUD",
    sqft: 1386,
    beds: 3,
    baths: 2,
    sections: "Multi-Section",
    price: "$85,000",
    priceNumeric: "85000",
    sku: "BRI-2852",
    description: "The Brighton 2852 offers 1,386 square feet of family-friendly living with vaulted ceilings that create an airy, spacious feel. Three bedrooms and two bathrooms accommodate growing families, while the open living and dining area is perfect for entertaining.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Brighton 2852 double wide home with vaulted ceilings and spacious layout",
    features: [
      "Vaulted Ceilings",
      "Spacious Family Room",
      "3 Bedrooms",
      "2 Full Bathrooms",
      "Open Living & Dining",
      "Master Suite",
      "Modern Kitchen",
      "Customizable Finishes",
    ],
    specs: {
      width: "28 ft",
      length: "52 ft",
      ceiling: "Vaulted ceilings",
      bedrooms: "3",
      bathrooms: "2 full",
      kitchen: "Open with dining area",
      living: "Family room with vaulted ceiling",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Brighton 2852 cost?", answer: "The Brighton 2852 starts at $85,000 for the base home, making it our most affordable double wide option. At 1,386 square feet with 3 bedrooms and vaulted ceilings, it offers strong value. Total installed cost depends on delivery distance, foundation, and site preparation. Contact us for a detailed line-item quote." },
      { question: "What makes the Brighton 2852 different from the 2856?", answer: "The Brighton 2852 is slightly smaller at 1,386 vs 1,493 square feet and costs $4,900 less. The 2852 features vaulted ceilings for an airy feel, while the 2856 has a split bedroom design with island kitchen. Both are 3-bedroom, 2-bathroom double wides. Choose based on your layout preference and budget." },
      { question: "Do vaulted ceilings make the home feel bigger?", answer: "Yes, vaulted ceilings significantly enhance the sense of space in the Brighton 2852. The higher ceiling in the main living area creates an open, airy atmosphere that makes the 1,386 square foot home feel much larger than its footprint. It's one of the most popular features buyers appreciate when visiting our showroom." },
      { question: "Can I customize the Brighton 2852?", answer: "Absolutely. Champion Homes offers extensive customization including flooring types, cabinetry styles, countertop materials, appliance packages, exterior colors, and interior finishes. The vaulted ceiling comes standard. Visit our Auburn showroom to walk through similar models and explore your customization options in person." },
      { question: "What is the delivery process for the Brighton 2852?", answer: "The Brighton 2852 is a multi-section home delivered in two halves on separate trucks. Each section is transported from Champion's Topeka factory to your prepared site. Our professional installers join the sections, complete the roof line, finish interior seams, and connect all utilities. The process takes 2 to 3 weeks after delivery." },
    ],
  },
  {
    slug: "silverton-2876",
    name: "Silverton 2876",
    series: "Silverton Series",
    type: "Double Wide",
    code: "HUD",
    sqft: 1493,
    beds: 4,
    baths: 2,
    sections: "Multi-Section",
    price: "$95,000",
    priceNumeric: "95000",
    sku: "SIL-2876",
    description: "The Silverton 2876 is built for larger families who need space. With 4 bedrooms, 2 bathrooms, and dual living areas in 1,493 square feet, this home offers a separate family room and formal living room. The extra bedroom and dual living spaces make it ideal for families with children.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Silverton 2876 four-bedroom double wide manufactured home",
    features: [
      "4 Bedrooms",
      "Dual Living Areas",
      "2 Full Bathrooms",
      "Family Room + Living Room",
      "Master Suite",
      "Modern Kitchen",
      "Ample Storage",
      "Customizable Finishes",
    ],
    specs: {
      width: "28 ft",
      length: "56 ft",
      ceiling: "8-9' ceilings",
      bedrooms: "4",
      bathrooms: "2 full",
      kitchen: "Full kitchen with dining",
      living: "Dual living areas",
      foundation: "Permanent or pier & beam",
      construction: "HUD Code",
    },
    faqs: [
      { question: "How much does the Silverton 2876 cost?", answer: "The Silverton 2876 starts at $95,000 for the base home. With 4 bedrooms and dual living areas, it offers exceptional value for larger families. Total installed cost varies based on your location, foundation type, and site work. We provide transparent line-item pricing so you know exactly what every component costs." },
      { question: "Why choose 4 bedrooms over 3?", answer: "The fourth bedroom gives families flexibility that grows with them. Use it as a children's room, home office, guest room, or hobby space. The Silverton 2876 fits 4 bedrooms into the same 1,493 square foot footprint as 3-bedroom models, so you get an extra room without a significantly larger home or higher cost." },
      { question: "What are dual living areas?", answer: "Dual living areas means the Silverton 2876 has both a formal living room and a separate family room. This gives families distinct spaces for different activities — a quiet living room for adults and a family room for children, TV, or casual gatherings. It's one of the most valued features for families with kids." },
      { question: "How does the Silverton compare to site-built 4-bedroom homes?", answer: "A new site-built 4-bedroom home in Indiana typically costs $250,000 to $350,000 or more. The Silverton 2876 delivers 4 bedrooms for under $100,000 base price. While square footage is more compact, the factory-built quality is excellent and you avoid the long construction timeline and cost overruns of site-built projects." },
      { question: "Can I finance the Silverton 2876?", answer: "Yes. At $95,000, the Silverton 2876 qualifies for chattel loans, FHA, VA, USDA, and conventional mortgages depending on your land and foundation situation. Monthly payments range from roughly $700 to $1,000 depending on your loan type and terms. We connect you with the right lender for your situation." },
    ],
  },
  {
    slug: "aspire-modular-2860",
    name: "Aspire Modular 2860",
    series: "Aspire Modular Series",
    type: "Modular",
    code: "IRC",
    sqft: 1680,
    beds: 3,
    baths: 2,
    sections: "Multi-Section",
    price: "$110,000",
    priceNumeric: "110000",
    sku: "ASM-2860",
    description: "The Aspire Modular 2860 offers 1,680 square feet of site-built quality at factory-direct prices. Featuring an open floor plan with mudroom entry, 3 bedrooms, and 2 bathrooms, this IRC-code home qualifies for conventional mortgages and is placed on a permanent foundation.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Aspire Modular 2860 modular home with open floor plan",
    features: [
      "Open Floor Plan",
      "Mudroom Entry",
      "3 Bedrooms",
      "2 Full Bathrooms",
      "IRC Building Code",
      "Permanent Foundation Ready",
      "Garage Ready",
      "Customizable Throughout",
    ],
    specs: {
      width: "28-32 ft",
      length: "56-76 ft",
      ceiling: "9' ceilings",
      bedrooms: "3",
      bathrooms: "2 full",
      kitchen: "Open concept with island",
      living: "Open floor plan with mudroom",
      foundation: "Permanent (required)",
      construction: "IRC Modular Code",
    },
    faqs: [
      { question: "How much does the Aspire Modular 2860 cost?", answer: "The Aspire Modular 2860 starts at $110,000 for the base home. As an IRC-code modular home, it requires a permanent foundation which adds to total cost. Complete installed pricing varies by location and site conditions. We provide full line-item transparency so you can budget accurately for your complete home project." },
      { question: "What is the difference between modular and manufactured?", answer: "The Aspire Modular 2860 is built to IRC (International Residential Code) — the same codes as site-built homes. Manufactured homes are built to federal HUD code. This means the 2860 qualifies for conventional mortgages, is treated as real property, and must be placed on a permanent foundation. Quality is comparable but financing and zoning options differ." },
      { question: "Does the Aspire Modular 2860 qualify for a conventional mortgage?", answer: "Yes. Because it's built to IRC code and placed on a permanent foundation, the Aspire Modular 2860 qualifies for conventional mortgages from Fannie Mae and Freddie Mac, plus FHA, VA, and USDA loans. This gives you access to the lowest interest rates and longest loan terms available for factory-built homes." },
      { question: "What foundation does the Aspire Modular 2860 need?", answer: "The Aspire Modular 2860 requires a permanent foundation — either a full basement, crawl space, or concrete slab. The foundation must be engineered and built to local building codes before the home is delivered. We can coordinate foundation work through our network of local contractors or work with your preferred builder." },
      { question: "How does the 2860 compare to the Emerald Sky?", answer: "Both are 3-bedroom, 2-bathroom modular homes at 1,680 square feet. The Aspire Modular 2860 features a mudroom entry and open floor plan, while the Emerald Sky includes a fireplace, kitchen island, and office/flex room. Both are built to IRC code. Your choice depends on which layout and features best fit your lifestyle." },
    ],
  },
  {
    slug: "aspire-modular-3268",
    name: "Aspire Modular 3268",
    series: "Aspire Modular Series",
    type: "Modular",
    code: "IRC",
    sqft: 2176,
    beds: 4,
    baths: 3,
    sections: "Multi-Section",
    price: "$135,000",
    priceNumeric: "135000",
    sku: "ASM-3268",
    description: "The Aspire Modular 3268 delivers luxury modular living in 2,176 square feet. With 4 bedrooms, 3 bathrooms, and a luxury master suite with en-suite and walk-in closet, this home rivals custom-built construction at a fraction of the cost and timeline.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Aspire Modular 3268 luxury four-bedroom modular home",
    features: [
      "Luxury Master Suite",
      "En-Suite Bathroom with Walk-in",
      "4 Bedrooms",
      "3 Full Bathrooms",
      "Spacious Living Areas",
      "IRC Building Code",
      "Permanent Foundation Ready",
      "Full Customization Available",
    ],
    specs: {
      width: "32 ft",
      length: "68 ft",
      ceiling: "9' ceilings",
      bedrooms: "4",
      bathrooms: "3 full",
      kitchen: "Large kitchen with island",
      living: "Open concept living/dining",
      foundation: "Permanent (required)",
      construction: "IRC Modular Code",
    },
    faqs: [
      { question: "How much does the Aspire Modular 3268 cost?", answer: "The Aspire Modular 3268 starts at $135,000 for the base home. At over 2,100 square feet with 4 bedrooms and 3 bathrooms, it offers exceptional value compared to site-built homes of similar size which typically cost $300,000 or more. Total installed cost includes foundation, delivery, setup, and site work." },
      { question: "What makes the master suite luxury?", answer: "The Aspire Modular 3268's master suite includes a spacious bedroom, en-suite bathroom with dual vanities, a walk-in shower, soaking tub option, and a generous walk-in closet. The suite is separated from other bedrooms for privacy. It's designed to feel like a retreat within your home, rivaling custom-built master suites." },
      { question: "Is 4 bedrooms and 3 bathrooms really available at this price?", answer: "Yes. Factory construction allows Champion Homes to build larger, higher-quality homes at lower cost than traditional site-built construction. The Aspire Modular 3268 delivers 2,176 square feet with 4 beds and 3 baths starting at $135,000. That's roughly $62 per square foot compared to $150+ for site-built homes." },
      { question: "Can I add a garage to the Aspire Modular 3268?", answer: "The Aspire Modular 3268 is garage-ready, meaning it's designed to connect to an attached or detached garage. The garage itself is built separately on-site. We can coordinate garage construction through local contractors or you can use your own builder. Many buyers add a 2 or 3-car garage to complete their home." },
      { question: "What financing is best for a $135,000 modular home?", answer: "For an IRC-code modular home on a permanent foundation, conventional mortgages offer the best rates. VA loans are ideal for veterans with zero down payment. FHA loans require just 3.5% down. At $135,000, monthly payments with a 30-year mortgage are approximately $850 to $1,050 depending on your rate and down payment." },
    ],
  },
  {
    slug: "aspire-modular-3276",
    name: "Aspire Modular 3276",
    series: "Aspire Modular Series",
    type: "Modular",
    code: "IRC",
    sqft: 2432,
    beds: 5,
    baths: 3,
    sections: "Multi-Section",
    price: "$145,000",
    priceNumeric: "145000",
    sku: "ASM-3276",
    description: "Our flagship home. The Aspire Modular 3276 is a 2,432 square foot multi-generational masterpiece with 5 bedrooms, 3 bathrooms, and full basement readiness. Designed for large families or those needing maximum space, this IRC-code modular home delivers custom-home living at factory-direct pricing.",
    heroImage: "/images/hero-home.jpg",
    heroImageAlt: "Aspire Modular 3276 five-bedroom multi-generational modular home",
    features: [
      "5 Bedrooms",
      "3 Full Bathrooms",
      "Multi-Generational Design",
      "Full Basement Ready",
      "Spacious Living Areas",
      "Large Kitchen",
      "IRC Building Code",
      "Maximum Customization",
    ],
    specs: {
      width: "32 ft",
      length: "76 ft",
      ceiling: "9' ceilings",
      bedrooms: "5",
      bathrooms: "3 full",
      kitchen: "Large kitchen with island and pantry",
      living: "Multiple living areas",
      foundation: "Permanent with basement option",
      construction: "IRC Modular Code",
    },
    faqs: [
      { question: "How much does the Aspire Modular 3276 cost?", answer: "The Aspire Modular 3276 starts at $145,000 for the base home — our largest and most feature-rich offering. A comparable 5-bedroom site-built home would cost $350,000 to $500,000 or more. Total installed cost with foundation, basement, delivery, and site work varies by project scope. We provide complete line-item pricing." },
      { question: "What does multi-generational design mean?", answer: "The Aspire Modular 3276's multi-generational layout provides distinct living zones within one home. With 5 bedrooms and 3 bathrooms, grandparents, parents, and children can all have their own private spaces while sharing common living areas. The design supports extended family living without feeling crowded." },
      { question: "Can I add a full basement?", answer: "Yes, the Aspire Modular 3276 is specifically designed to be basement-ready. A full basement adds significant living and storage space below the main floor. The basement is constructed on-site before the modular sections are placed on top. This can effectively double your usable square footage for a modest additional investment." },
      { question: "Is 5 bedrooms the largest home you offer?", answer: "Yes, the Aspire Modular 3276 is currently our largest floor plan at 2,432 square feet with 5 bedrooms and 3 bathrooms. With a full basement, total usable space can exceed 4,800 square feet. For even larger needs, we can discuss custom configurations or contact Champion directly about specialty builds." },
      { question: "What is the delivery process for such a large home?", answer: "The Aspire Modular 3276 arrives in multiple sections on separate trucks. Each section is craned onto your prepared permanent foundation. Professional installers join sections, complete the roof, finish all interior connections, and ensure everything meets IRC building codes. The process takes 2 to 4 weeks after the foundation is ready." },
    ],
  },
];

// Get a floor plan by slug
export function getFloorPlanBySlug(slug: string): FloorPlan | undefined {
  return floorPlans.find((p) => p.slug === slug);
}

// Get all floor plan slugs (for generateStaticParams)
export function getAllFloorPlanSlugs(): string[] {
  return floorPlans.map((p) => p.slug);
}

// Get related floor plans (same type, excluding current)
export function getRelatedFloorPlans(slug: string, count = 3): FloorPlan[] {
  const current = floorPlans.find((p) => p.slug === slug);
  if (!current) return floorPlans.slice(0, count);
  return floorPlans
    .filter((p) => p.slug !== slug)
    .sort((a, b) => {
      const aTypeMatch = a.type === current.type ? 1 : 0;
      const bTypeMatch = b.type === current.type ? 1 : 0;
      return bTypeMatch - aTypeMatch;
    })
    .slice(0, count);
}
