// Repo-published Champion PRIME Series floor plans, merged with the CMS/feed
// catalog in api-content.ts (same pattern as local blog posts). Source of
// truth: the recovered FDHC 2026 retail price sheet + src/lib/pricing.ts —
// published from the repo because these models were never entered into the
// CMS. Specs (sqft/beds/baths/dimensions) come straight from the sheet.
// No photos yet: cards render the "No photo" placeholder until images are
// added. Dollar amounts stay internal — display pricing goes through the
// same SHOW_PRICES gate as every other home.

export interface LocalFloorPlan {
  slug: string;
  name: string;
  modelNumber: string;
  sqft: number;
  beds: number;
  baths: number;
  width: string;
  length: string;
  msrp: number;      // internal reference, not displayed while SHOW_PRICES is off
  fdhcPrice: number; // internal reference, not displayed while SHOW_PRICES is off
}

export const PRIME_SERIES = "Prime";
export const PRIME_HOME_TYPE = "Single Wide";

export function primeDescription(p: LocalFloorPlan): string {
  return `The ${p.name} is a ${p.beds}-bedroom, ${p.baths}-bath Champion PRIME Series single wide — ${p.sqft.toLocaleString("en-US")} sq ft at ${p.width} × ${p.length}. Built at Champion's Decatur, Indiana plant and sold factory-direct from our Auburn showroom with line-item pricing. Contact us for your factory-direct quote.`;
}

export const localFloorPlans: LocalFloorPlan[] = [
  {
    slug: "prime-peak",
    name: "Peak",
    modelNumber: "PEAK",
    sqft: 784,
    beds: 2,
    baths: 1,
    width: "16'",
    length: "52'",
    msrp: 49812,
    fdhcPrice: 44831,
  },
  {
    slug: "prime-peak-reverse-aisle",
    name: "Peak Reverse Aisle",
    modelNumber: "PEAK-RA",
    sqft: 784,
    beds: 2,
    baths: 1,
    width: "16'",
    length: "52'",
    msrp: 49812,
    fdhcPrice: 44831,
  },
  {
    slug: "prime-crest",
    name: "Crest",
    modelNumber: "CREST",
    sqft: 840,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52962,
    fdhcPrice: 47666,
  },
  {
    slug: "prime-crest-reverse-aisle",
    name: "Crest Reverse Aisle",
    modelNumber: "CREST-RA",
    sqft: 840,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52962,
    fdhcPrice: 47666,
  },
  {
    slug: "prime-zenith",
    name: "Zenith",
    modelNumber: "ZENITH",
    sqft: 924,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 56637,
    fdhcPrice: 50973,
  },
  {
    slug: "prime-zenith-reverse-aisle",
    name: "Zenith Reverse Aisle",
    modelNumber: "ZENITH-RA",
    sqft: 924,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 56637,
    fdhcPrice: 50973,
  },
  {
    slug: "prime-pike",
    name: "Pike",
    modelNumber: "PIKE",
    sqft: 576,
    beds: 2,
    baths: 1,
    width: "14'",
    length: "44'",
    msrp: 43867,
    fdhcPrice: 39480,
  },
  {
    slug: "prime-fulton",
    name: "Fulton",
    modelNumber: "FULTON",
    sqft: 768,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "48'",
    msrp: 49642,
    fdhcPrice: 44678,
  },
  {
    slug: "prime-fulton-reverse-aisle",
    name: "Fulton Reverse Aisle",
    modelNumber: "FULTON-RA",
    sqft: 768,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "48'",
    msrp: 49642,
    fdhcPrice: 44678,
  },
  {
    slug: "prime-gallatin",
    name: "Gallatin",
    modelNumber: "GALLATIN",
    sqft: 832,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "52'",
    msrp: 51292,
    fdhcPrice: 46163,
  },
  {
    slug: "prime-gallatin-reverse-aisle",
    name: "Gallatin Reverse Aisle",
    modelNumber: "GALLATIN-RA",
    sqft: 832,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "52'",
    msrp: 51292,
    fdhcPrice: 46163,
  },
  {
    slug: "prime-barkley",
    name: "Barkley",
    modelNumber: "BARKLEY",
    sqft: 896,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52898,
    fdhcPrice: 47608,
  },
  {
    slug: "prime-barkley-reverse-aisle",
    name: "Barkley Reverse Aisle",
    modelNumber: "BARKLEY-RA",
    sqft: 896,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52898,
    fdhcPrice: 47608,
  },
  {
    slug: "prime-spire",
    name: "Spire",
    modelNumber: "SPIRE",
    sqft: 960,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 54982,
    fdhcPrice: 49484,
  },
  {
    slug: "prime-spire-reverse-aisle",
    name: "Spire Reverse Aisle",
    modelNumber: "SPIRE-RA",
    sqft: 960,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 54982,
    fdhcPrice: 49484,
  },
  {
    slug: "prime-casey",
    name: "Casey",
    modelNumber: "CASEY",
    sqft: 960,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 56432,
    fdhcPrice: 50789,
  },
  {
    slug: "prime-vertex",
    name: "Vertex",
    modelNumber: "VERTEX",
    sqft: 1056,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "60'",
    msrp: 61157,
    fdhcPrice: 55041,
  },
  {
    slug: "prime-vertex-reverse-aisle",
    name: "Vertex Reverse Aisle",
    modelNumber: "VERTEX-RA",
    sqft: 1056,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "60'",
    msrp: 61157,
    fdhcPrice: 55041,
  },
  {
    slug: "prime-hickman",
    name: "Hickman",
    modelNumber: "HICKMAN",
    sqft: 1056,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "60'",
    msrp: 64257,
    fdhcPrice: 57831,
  },
  {
    slug: "prime-pendleton",
    name: "Pendleton",
    modelNumber: "PENDLETON",
    sqft: 1056,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "60'",
    msrp: 64257,
    fdhcPrice: 57831,
  },
  {
    slug: "prime-bardstown",
    name: "Bardstown",
    modelNumber: "BARDSTOWN",
    sqft: 1152,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "64'",
    msrp: 62157,
    fdhcPrice: 55941,
  },
  {
    slug: "prime-bardstown-reverse-aisle",
    name: "Bardstown Reverse Aisle",
    modelNumber: "BARDSTOWN-RA",
    sqft: 1152,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "64'",
    msrp: 62157,
    fdhcPrice: 55941,
  },
  {
    slug: "prime-ballard",
    name: "Ballard",
    modelNumber: "BALLARD",
    sqft: 1152,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "64'",
    msrp: 65257,
    fdhcPrice: 58731,
  },
  {
    slug: "prime-powell",
    name: "Powell",
    modelNumber: "POWELL",
    sqft: 1152,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "64'",
    msrp: 65257,
    fdhcPrice: 58731,
  },
  {
    slug: "prime-ridge",
    name: "Ridge",
    modelNumber: "RIDGE",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 65943,
    fdhcPrice: 59349,
  },
  {
    slug: "prime-ridge-reverse-aisle",
    name: "Ridge Reverse Aisle",
    modelNumber: "RIDGE-RA",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 65943,
    fdhcPrice: 59349,
  },
  {
    slug: "prime-monte",
    name: "Monte",
    modelNumber: "MONTE",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 67732,
    fdhcPrice: 60959,
  },
  {
    slug: "prime-monte-reverse-aisle",
    name: "Monte Reverse Aisle",
    modelNumber: "MONTE-RA",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 67732,
    fdhcPrice: 60959,
  },
  {
    slug: "prime-somerset",
    name: "Somerset",
    modelNumber: "SOMERSET",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 68232,
    fdhcPrice: 61409,
  },
  {
    slug: "prime-floyd",
    name: "Floyd",
    modelNumber: "FLOYD",
    sqft: 1216,
    beds: 3,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 68232,
    fdhcPrice: 61409,
  },
  {
    slug: "prime-plateau",
    name: "Plateau",
    modelNumber: "PLATEAU",
    sqft: 1152,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "64'",
    msrp: 77030,
    fdhcPrice: 69327,
  },
  {
    slug: "prime-horizon",
    name: "Horizon",
    modelNumber: "HORIZON",
    sqft: 1344,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "76'",
    msrp: 82207,
    fdhcPrice: 73986,
  },
  {
    slug: "prime-estill",
    name: "Estill",
    modelNumber: "ESTILL",
    sqft: 1232,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "68'",
    msrp: 75419,
    fdhcPrice: 67877,
  },
  {
    slug: "prime-churchill",
    name: "Churchill",
    modelNumber: "CHURCHILL",
    sqft: 1344,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "76'",
    msrp: 79107,
    fdhcPrice: 71196,
  },
  {
    slug: "prime-mercer",
    name: "Mercer",
    modelNumber: "MERCER",
    sqft: 1456,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "80'",
    msrp: 81442,
    fdhcPrice: 73298,
  },
  {
    slug: "prime-apex",
    name: "Apex",
    modelNumber: "APEX",
    sqft: 1568,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "88'",
    msrp: 83862,
    fdhcPrice: 75476,
  },
  {
    slug: "prime-crown",
    name: "Crown",
    modelNumber: "CROWN",
    sqft: 1568,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "88'",
    msrp: 85212,
    fdhcPrice: 76691,
  },
  {
    slug: "prime-the-grand",
    name: "The Grand",
    modelNumber: "THE-GRAND",
    sqft: 1904,
    beds: 5,
    baths: 3,
    width: "18'",
    length: "108'",
    msrp: 99532,
    fdhcPrice: 89579,
  },
  {
    slug: "prime-pinnacle",
    name: "Pinnacle",
    modelNumber: "PINNACLE",
    sqft: 1568,
    beds: 4,
    baths: 2,
    width: "18'",
    length: "88'",
    msrp: 108442,
    fdhcPrice: 97598,
  },
];
