// Repo-published Champion PRIME Series floor plans, merged with the CMS/feed
// catalog in api-content.ts (same pattern as local blog posts) — published
// from the repo because these models were never entered into the CMS.
// Specs (conditioned sq ft, beds/baths, nominal dimensions) come from
// Champion's own PRIME literature/floor-plan drawings (Box: Decatur IN/
// Prime/Literature + Floor Plans) — NOT computed from box dimensions; the
// old price-sheet figures were box areas, which overstate living space.
// Fulton and Gallatin have no Champion literature in the library yet, so
// their sheet figures remain pending factory confirmation. Ridge's drawing
// (1676H32P01) misprints "1533 sq ft" — physically impossible for a
// 15'2" x 76' box; 1153 (the value on Champion's identical-box 1676 plans)
// is used instead. Cards without photos render the placeholder until images are
// added. Dollar amounts stay internal — display pricing goes through the
// same SHOW_PRICES gate as every other home.

export interface LocalFloorPlan {
  slug: string;
  name: string;
  modelNumber: string;
  sqft: number;
  beds: number;
  baths: number;
  width: string;
  length: string;
  msrp: number;      // internal reference, not displayed while SHOW_PRICES is off
  fdhcPrice: number; // internal reference, not displayed while SHOW_PRICES is off
  homeType?: string; // "Double Wide" for multi-section models; defaults to Single Wide
  virtualTour?: string; // Matterport / 3D Vista link from Champion's Decatur tour sheet
  image?: string;    // banner/card photo (site-relative), from Champion's Prime media library
  gallery?: string[]; // detail-page gallery, banner first
}

export const PRIME_SERIES = "Prime";
export const PRIME_HOME_TYPE = "Single Wide";

export function primeDescription(p: LocalFloorPlan): string {
  return `The ${p.name} is a ${p.beds}-bedroom, ${p.baths}-bath Champion PRIME Series ${(p.homeType || PRIME_HOME_TYPE).toLowerCase()} — ${p.sqft.toLocaleString("en-US")} sq ft of conditioned living space at ${p.width} × ${p.length}. Built at Champion's Decatur, Indiana plant and sold factory-direct from our Auburn showroom with line-item pricing. Contact us for your factory-direct quote.`;
}

export const localFloorPlans: LocalFloorPlan[] = [
  {
    slug: "prime-peak",
    name: "Peak",
    modelNumber: "1456H22P01",
    sqft: 746,
    beds: 2,
    baths: 2,
    width: "14'",
    length: "56'",
    msrp: 49812,
    fdhcPrice: 44831,
  },
  {
    slug: "prime-peak-reverse-aisle",
    name: "Peak Reverse Aisle",
    modelNumber: "PEAK-RA",
    sqft: 746,
    beds: 2,
    baths: 2,
    width: "14'",
    length: "56'",
    msrp: 49812,
    fdhcPrice: 44831,
  },
  {
    slug: "prime-crest",
    name: "Crest",
    modelNumber: "1460H22P01",
    sqft: 800,
    beds: 2,
    baths: 2,
    width: "14'",
    length: "60'",
    msrp: 52962,
    fdhcPrice: 47666,
  },
  {
    slug: "prime-crest-reverse-aisle",
    name: "Crest Reverse Aisle",
    modelNumber: "CREST-RA",
    sqft: 800,
    beds: 2,
    baths: 2,
    width: "14'",
    length: "60'",
    msrp: 52962,
    fdhcPrice: 47666,
  },
  {
    slug: "prime-zenith",
    name: "Zenith",
    modelNumber: "1466H32P01",
    sqft: 880,
    beds: 3,
    baths: 2,
    width: "14'",
    length: "66'",
    msrp: 56637,
    fdhcPrice: 50973,
  },
  {
    slug: "prime-zenith-reverse-aisle",
    name: "Zenith Reverse Aisle",
    modelNumber: "ZENITH-RA",
    sqft: 880,
    beds: 3,
    baths: 2,
    width: "14'",
    length: "66'",
    msrp: 56637,
    fdhcPrice: 50973,
  },
  {
    slug: "prime-pike",
    name: "Pike",
    modelNumber: "1636H11P01",
    sqft: 546,
    beds: 1,
    baths: 1,
    width: "16'",
    length: "36'",
    msrp: 43867,
    fdhcPrice: 39480,
  },
  {
    slug: "prime-fulton",
    name: "Fulton",
    modelNumber: "FULTON",
    sqft: 768,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "48'",
    msrp: 49642,
    fdhcPrice: 44678,
  },
  {
    slug: "prime-fulton-reverse-aisle",
    name: "Fulton Reverse Aisle",
    modelNumber: "FULTON-RA",
    sqft: 768,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "48'",
    msrp: 49642,
    fdhcPrice: 44678,
  },
  {
    slug: "prime-gallatin",
    name: "Gallatin",
    modelNumber: "GALLATIN",
    sqft: 832,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "52'",
    msrp: 51292,
    fdhcPrice: 46163,
  },
  {
    slug: "prime-gallatin-reverse-aisle",
    name: "Gallatin Reverse Aisle",
    modelNumber: "GALLATIN-RA",
    sqft: 832,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "52'",
    msrp: 51292,
    fdhcPrice: 46163,
  },
  {
    slug: "prime-barkley",
    name: "Barkley",
    modelNumber: "1656H22P01",
    sqft: 849,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52898,
    fdhcPrice: 47608,
  },
  {
    slug: "prime-barkley-reverse-aisle",
    name: "Barkley Reverse Aisle",
    modelNumber: "BARKLEY-RA",
    sqft: 849,
    beds: 2,
    baths: 2,
    width: "16'",
    length: "56'",
    msrp: 52898,
    fdhcPrice: 47608,
  },
  {
    slug: "prime-spire",
    name: "Spire",
    modelNumber: "1660H32P05",
    sqft: 910,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 54982,
    fdhcPrice: 49484,
  },
  {
    slug: "prime-spire-reverse-aisle",
    name: "Spire Reverse Aisle",
    modelNumber: "SPIRE-RA",
    sqft: 910,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 54982,
    fdhcPrice: 49484,
  },
  {
    slug: "prime-casey",
    name: "Casey",
    modelNumber: "CASEY",
    sqft: 910,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "60'",
    msrp: 56432,
    fdhcPrice: 50789,
  },
  {
    slug: "prime-vertex",
    name: "Vertex",
    modelNumber: "1666H32P01",
    sqft: 1001,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "66'",
    msrp: 61157,
    fdhcPrice: 55041,
    virtualTour: "https://my.matterport.com/show/?m=x29bKjegwxW",
    image: "/images/prime/vertex-exterior-2.webp",
    gallery: ["/images/prime/vertex-exterior-2.webp", "/images/prime/vertex-exterior-1.webp", "/images/prime/vertex-living-room.webp", "/images/prime/vertex-kitchen.webp", "/images/prime/vertex-dining.webp", "/images/prime/vertex-primary-bedroom.webp", "/images/prime/vertex-primary-bath.webp", "/images/prime/vertex-bedroom.webp"],
  },
  {
    slug: "prime-vertex-reverse-aisle",
    name: "Vertex Reverse Aisle",
    modelNumber: "VERTEX-RA",
    sqft: 1001,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "66'",
    msrp: 61157,
    fdhcPrice: 55041,
    virtualTour: "https://my.matterport.com/show/?m=x29bKjegwxW",
    image: "/images/prime/vertex-exterior-2.webp",
    gallery: ["/images/prime/vertex-exterior-2.webp", "/images/prime/vertex-exterior-1.webp", "/images/prime/vertex-living-room.webp", "/images/prime/vertex-kitchen.webp", "/images/prime/vertex-dining.webp", "/images/prime/vertex-primary-bedroom.webp", "/images/prime/vertex-primary-bath.webp", "/images/prime/vertex-bedroom.webp"],
  },
  {
    slug: "prime-hickman",
    name: "Hickman",
    modelNumber: "HICKMAN",
    sqft: 1001,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "66'",
    msrp: 64257,
    fdhcPrice: 57831,
  },
  {
    slug: "prime-pendleton",
    name: "Pendleton",
    modelNumber: "1666H32P09",
    sqft: 1001,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "66'",
    msrp: 64257,
    fdhcPrice: 57831,
  },
  {
    slug: "prime-bardstown",
    name: "Bardstown",
    modelNumber: "BARDSTOWN",
    sqft: 1092,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "72'",
    msrp: 62157,
    fdhcPrice: 55941,
  },
  {
    slug: "prime-bardstown-reverse-aisle",
    name: "Bardstown Reverse Aisle",
    modelNumber: "BARDSTOWN-RA",
    sqft: 1092,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "72'",
    msrp: 62157,
    fdhcPrice: 55941,
  },
  {
    slug: "prime-ballard",
    name: "Ballard",
    modelNumber: "BALLARD",
    sqft: 1092,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "72'",
    msrp: 65257,
    fdhcPrice: 58731,
  },
  {
    slug: "prime-powell",
    name: "Powell",
    modelNumber: "1672H32P09",
    sqft: 1092,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "72'",
    msrp: 65257,
    fdhcPrice: 58731,
  },
  {
    slug: "prime-ridge",
    name: "Ridge",
    modelNumber: "1676H32P01",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 65943,
    fdhcPrice: 59349,
    virtualTour: "https://my.matterport.com/show/?m=oGGVXBkLNVC",
    image: "/images/prime/ridge-living-room.webp",
    gallery: ["/images/prime/ridge-living-room.webp", "/images/prime/ridge-kitchen-1.webp", "/images/prime/ridge-kitchen-2.webp", "/images/prime/ridge-dining.webp", "/images/prime/ridge-primary-bedroom.webp", "/images/prime/ridge-primary-bath.webp"],
  },
  {
    slug: "prime-ridge-reverse-aisle",
    name: "Ridge Reverse Aisle",
    modelNumber: "RIDGE-RA",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 65943,
    fdhcPrice: 59349,
    virtualTour: "https://my.matterport.com/show/?m=oGGVXBkLNVC",
    image: "/images/prime/ridge-living-room.webp",
    gallery: ["/images/prime/ridge-living-room.webp", "/images/prime/ridge-kitchen-1.webp", "/images/prime/ridge-kitchen-2.webp", "/images/prime/ridge-dining.webp", "/images/prime/ridge-primary-bedroom.webp", "/images/prime/ridge-primary-bath.webp"],
  },
  {
    slug: "prime-monte",
    name: "Monte",
    modelNumber: "MONTE",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 67732,
    fdhcPrice: 60959,
    virtualTour: "https://my.matterport.com/show/?m=C98XzbqCou8",
    image: "/images/prime/monte-exterior-1.webp",
    gallery: ["/images/prime/monte-exterior-1.webp", "/images/prime/monte-exterior-2.webp", "/images/prime/monte-living-room.webp", "/images/prime/monte-kitchen.webp", "/images/prime/monte-dining.webp", "/images/prime/monte-primary-bedroom.webp", "/images/prime/monte-primary-bath.webp", "/images/prime/monte-bedroom.webp"],
  },
  {
    slug: "prime-monte-reverse-aisle",
    name: "Monte Reverse Aisle",
    modelNumber: "MONTE-RA",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 67732,
    fdhcPrice: 60959,
    virtualTour: "https://my.matterport.com/show/?m=C98XzbqCou8",
    image: "/images/prime/monte-exterior-1.webp",
    gallery: ["/images/prime/monte-exterior-1.webp", "/images/prime/monte-exterior-2.webp", "/images/prime/monte-living-room.webp", "/images/prime/monte-kitchen.webp", "/images/prime/monte-dining.webp", "/images/prime/monte-primary-bedroom.webp", "/images/prime/monte-primary-bath.webp", "/images/prime/monte-bedroom.webp"],
  },
  {
    slug: "prime-somerset",
    name: "Somerset",
    modelNumber: "SOMERSET",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 68232,
    fdhcPrice: 61409,
  },
  {
    slug: "prime-floyd",
    name: "Floyd",
    modelNumber: "1676H32P09",
    sqft: 1153,
    beds: 3,
    baths: 2,
    width: "16'",
    length: "76'",
    msrp: 68232,
    fdhcPrice: 61409,
    image: "/images/prime/floyd-rendering.webp",
    gallery: ["/images/prime/floyd-rendering.webp"],
  },
  {
    slug: "prime-plateau",
    name: "Plateau",
    modelNumber: "2448H32P02",
    sqft: 1120,
    beds: 3,
    baths: 2,
    width: "24'",
    length: "48'",
    homeType: "Double Wide",
    msrp: 77030,
    fdhcPrice: 69327,
  },
  {
    slug: "prime-horizon",
    name: "Horizon",
    modelNumber: "2848H32P02",
    sqft: 1280,
    beds: 3,
    baths: 2,
    width: "28'",
    length: "48'",
    homeType: "Double Wide",
    msrp: 82207,
    fdhcPrice: 73986,
  },
  {
    slug: "prime-estill",
    name: "Estill",
    modelNumber: "2844H32P01",
    sqft: 1173,
    beds: 3,
    baths: 2,
    width: "28'",
    length: "44'",
    homeType: "Double Wide",
    msrp: 75419,
    fdhcPrice: 67877,
  },
  {
    slug: "prime-churchill",
    name: "Churchill",
    modelNumber: "2848H32P06",
    sqft: 1284,
    beds: 3,
    baths: 2,
    width: "28'",
    length: "48'",
    homeType: "Double Wide",
    msrp: 79107,
    fdhcPrice: 71196,
    virtualTour: "https://storage.net-fs.com/hosting/8433117/3/",
  },
  {
    slug: "prime-mercer",
    name: "Mercer",
    modelNumber: "2852H32P01",
    sqft: 1387,
    beds: 3,
    baths: 2,
    width: "28'",
    length: "52'",
    homeType: "Double Wide",
    msrp: 81442,
    fdhcPrice: 73298,
  },
  {
    slug: "prime-apex",
    name: "Apex",
    modelNumber: "2856H32P01",
    sqft: 1493,
    beds: 3,
    baths: 2,
    width: "28'",
    length: "56'",
    homeType: "Double Wide",
    msrp: 83862,
    fdhcPrice: 75476,
    virtualTour: "https://storage.net-fs.com/hosting/8433117/4/",
  },
  {
    slug: "prime-crown",
    name: "Crown",
    modelNumber: "2856H42P01",
    sqft: 1493,
    beds: 4,
    baths: 2,
    width: "28'",
    length: "56'",
    homeType: "Double Wide",
    msrp: 85212,
    fdhcPrice: 76691,
  },
  {
    slug: "prime-the-grand",
    name: "The Grand",
    modelNumber: "2868H42P01",
    sqft: 1813,
    beds: 4,
    baths: 2,
    width: "28'",
    length: "68'",
    homeType: "Double Wide",
    msrp: 99532,
    fdhcPrice: 89579,
    virtualTour: "https://my.matterport.com/show/?m=mDLEKL5MrLc",
    image: "/images/prime/the-grand-exterior-1.webp",
    gallery: ["/images/prime/the-grand-exterior-1.webp", "/images/prime/the-grand-elevation.webp", "/images/prime/the-grand-exterior-2.webp", "/images/prime/the-grand-living-room.webp", "/images/prime/the-grand-kitchen.webp", "/images/prime/the-grand-dining.webp", "/images/prime/the-grand-family-room.webp", "/images/prime/the-grand-primary-bedroom.webp", "/images/prime/the-grand-primary-bath.webp"],
  },
  {
    slug: "prime-pinnacle",
    name: "Pinnacle",
    modelNumber: "2876H53P01",
    sqft: 2027,
    beds: 5,
    baths: 3,
    width: "28'",
    length: "76'",
    homeType: "Double Wide",
    msrp: 108442,
    fdhcPrice: 97598,
    virtualTour: "https://storage.net-fs.com/hosting/8433117/7/",
  },
];
